# Generated by Django 4.2.7 on 2023-12-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Картинка объекта', 'verbose_name_plural': 'Картинки объекта'},
        ),
        migrations.AlterModelOptions(
            name='roomtypeimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Картинка номера', 'verbose_name_plural': 'Картинки номера'},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='roomtypeimage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
