# Generated by Django 4.2.7 on 2023-12-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['sort_order'], 'verbose_name': 'Тип размещения', 'verbose_name_plural': 'Типы размещения'},
        ),
        migrations.AddField(
            model_name='roomtype',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
