# Generated by Django 4.2.7 on 2023-12-14 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_options_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('tl_id', models.IntegerField(blank=True, null=True, verbose_name='TL id')),
                ('name', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('currency', models.CharField(default='RUB', max_length=16, verbose_name='Currency')),
                ('with_children_only', models.BooleanField(default=False, verbose_name='With children only')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='properties.property')),
            ],
            options={
                'verbose_name': 'Rate plan',
                'verbose_name_plural': 'Rate plans',
                'ordering': ['sort_order'],
            },
        ),
    ]
