# Generated by Django 4.2.7 on 2023-12-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rateplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rateplan',
            options={'verbose_name': 'Rate plan', 'verbose_name_plural': 'Rate plans'},
        ),
        migrations.RemoveField(
            model_name='rateplan',
            name='sort_order',
        ),
    ]
