# Generated by Django 4.2.7 on 2023-12-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='check_in_time',
            field=models.TimeField(default='14:00', verbose_name='Check-in time'),
        ),
        migrations.AddField(
            model_name='property',
            name='check_out_time',
            field=models.TimeField(default='12:00', verbose_name='Check-out time'),
        ),
    ]
