# Generated by Django 4.2.7 on 2023-12-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_check_in_time_property_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='time_zone',
            field=models.CharField(default='Europe/Moscow', max_length=32),
        ),
    ]
