# Generated by Django 4.2.7 on 2023-12-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='beds',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Beds count'),
        ),
    ]
