# Generated by Django 5.0 on 2023-12-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_roomtype_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Storeys'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='elevator',
            field=models.BooleanField(blank=True, null=True, verbose_name='Elevator'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Beds count'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='storey',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Storey'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='storeys',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Storeys'),
        ),
    ]
