# Generated by Django 4.2.9 on 2024-01-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_tl_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='non_smoking',
            field=models.BooleanField(blank=True, null=True, verbose_name='Non smoking room'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rooms count'),
        ),
    ]
