# Generated by Django 4.2.10 on 2024-02-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_roomtype_non_smoking_alter_roomtype_bedrooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rateplan',
            old_name='property',
            new_name='property_obj',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='property',
            new_name='property_obj',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='property',
            new_name='property_obj',
        ),
    ]
