# Generated by Django 5.0.4 on 2024-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_rename_property_rateplan_property_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.CharField(blank=True, choices=[('reho24', 'REHO24')], max_length=50, null=True, verbose_name='Собственник'),
        ),
    ]
