# Generated by Django 4.2.7 on 2023-12-07 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_trigram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='amenitycategory',
            options={'verbose_name': 'Amenity category', 'verbose_name_plural': 'Amenity categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='roomtypecategory',
            options={'verbose_name': 'Room type category', 'verbose_name_plural': 'Room type categories'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=128, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=16, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='amenity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='shared.amenitycategory', verbose_name='Amenity category'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='code',
            field=models.CharField(max_length=64, verbose_name='TL code'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='amenitycategory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='shared.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='city',
            name='tl_id',
            field=models.PositiveIntegerField(verbose_name='TL id'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='region',
            name='tl_id',
            field=models.PositiveIntegerField(verbose_name='TL id'),
        ),
        migrations.AlterField(
            model_name='roomtypecategory',
            name='code',
            field=models.CharField(max_length=16, verbose_name='TL code'),
        ),
        migrations.AlterField(
            model_name='roomtypecategory',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Title'),
        ),
    ]
