# Generated by Django 5.0.4 on 2024-04-27 08:41

import apps.shared.models.property_owner_contacts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_mealplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwnerContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('reho24', 'REHO24')], default=apps.shared.models.property_owner_contacts.PropertyOwner['REHO24'], max_length=50, verbose_name='Собственник')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакты собственников объектов',
                'verbose_name_plural': 'Контакты собственников объектов',
            },
        ),
    ]
