# Generated by Django 4.2.7 on 2023-12-22 10:21

import apps.bookings.models.booking
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_roomtype_beds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_alter_search_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('adults', models.PositiveSmallIntegerField()),
                ('children', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, size=None)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('number', models.CharField(max_length=64, verbose_name='Number')),
                ('status', models.CharField(choices=[('VERIFIED', 'verified'), ('CREATED', 'created'), ('CANCELLED', 'cancelled')], default=apps.bookings.models.booking.BookingStatus['VERIFIED'], max_length=32, verbose_name='Status')),
                ('placements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None, verbose_name='Bed types')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default=apps.bookings.models.booking.Currency['RUB'], max_length=8, verbose_name='Currency')),
                ('price_before_tax', models.FloatField(default=0, verbose_name='Price before tax')),
                ('tax', models.FloatField(default=0, verbose_name='Tax amount')),
                ('price_total', models.FloatField(default=0, verbose_name='Total price')),
                ('prepayment', models.FloatField(default=0, verbose_name='Prepayment')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('create_token', models.CharField(max_length=512, null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.property')),
                ('rate_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.rateplan')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.roomtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('amount', models.FloatField(default=0)),
                ('refund', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VERIFIED', 'verified'), ('CREATED', 'created'), ('CANCELLED', 'cancelled')], max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDailyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_date', models.DateField()),
                ('price_before_tax', models.FloatField(verbose_name='Price before tax')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to='bookings.booking')),
            ],
        ),
    ]
