# Generated by Django 5.0 on 2023-12-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_status_alter_bookinghistory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingdailyrate',
            options={'verbose_name': 'Booking daily rate', 'verbose_name_plural': 'Booking daily rates'},
        ),
        migrations.AlterModelOptions(
            name='bookinghistory',
            options={'verbose_name': 'Booking history', 'verbose_name_plural': 'Booking history'},
        ),
    ]
