# Generated by Django 5.0 on 2023-12-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_payment_status_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tl_request_memo',
            field=models.TextField(blank=True, null=True, verbose_name='TL request memo'),
        ),
    ]
