# Generated by Django 5.0 on 2023-12-25 15:57

import apps.bookings.models.booking
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_tl_request_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('verified', 'VERIFIED'), ('confirmed', 'CONFIRMED'), ('cancelled', 'CANCELLED')], default=apps.bookings.models.booking.BookingStatus['VERIFIED'], max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='status',
            field=models.CharField(choices=[('verified', 'VERIFIED'), ('confirmed', 'CONFIRMED'), ('cancelled', 'CANCELLED')], max_length=32),
        ),
    ]
