# Generated by Django 5.0 on 2023-12-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_locked_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
