# Generated by Django 5.0 on 2023-12-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rating_comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Rating comment'),
        ),
    ]
