# Generated by Django 4.2.9 on 2024-01-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_rating_booking_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation policy'),
        ),
    ]
