# Generated by Django 4.2.9 on 2024-02-13 11:59

from django.db import migrations, models
import django.db.models.deletion
import external.paykeeper.schemas
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_cancellation_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paykeeper_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PayKeeper ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('obtained', 'OBTAINED'), ('canceled', 'CANCELED'), ('success', 'SUCCESS'), ('failed', 'FAILED'), ('stuck', 'STUCK'), ('refunded', 'REFUNDED'), ('refunding', 'REFUNDING'), ('partially_refunded', 'PARTIALLY_REFUNDED')], default=external.paykeeper.schemas.PaymentStatus['PENDING'], max_length=32, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('done', 'DONE'), ('failed', 'FAILED')], default=external.paykeeper.schemas.RefundStatus['STARTED'], max_length=32, verbose_name='Status')),
                ('paykeeper_id', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PayKeeper ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bookings.payment')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
            },
        ),
    ]
