# Generated by Django 4.2.10 on 2024-02-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='corrupted',
            field=models.BooleanField(default=False),
        ),
    ]
