# Generated by Django 4.2.10 on 2024-02-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_payment_paykeeper_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='property',
            new_name='property_obj',
        ),
    ]
