# Generated by Django 4.2.10 on 2024-02-29 09:06

import apps.bookings.models.booking
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_rename_property_booking_property_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('verified', 'VERIFIED'), ('confirmed', 'CONFIRMED'), ('rejected', 'REJECTED'), ('cancelled', 'CANCELLED'), ('outdated', 'OUTDATED')], default=apps.bookings.models.booking.BookingStatus['VERIFIED'], max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='status',
            field=models.CharField(choices=[('verified', 'VERIFIED'), ('confirmed', 'CONFIRMED'), ('rejected', 'REJECTED'), ('cancelled', 'CANCELLED'), ('outdated', 'OUTDATED')], max_length=32),
        ),
    ]
